name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*
  - packages/samples/*
  - packages/utils/*
  - samples/*

scripts:
  # dependsOn で or 条件で指定することができないため
  # スクリプトを Flutter と Dart に分けている
  test:
    steps:
      - test:flutter
      - test:dart

  test:flutter:
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: flutter_test
      dirExists: test

  test:dart:
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: test
      dirExists: test

  # dependsOn で or 条件で指定することができないため
  # スクリプトを Flutter と Dart に分けている
  report:test:
    steps:
      - report:test:flutter
      - report:test:dart

  report:test:flutter:
    run: flutter test --no-pub --machine > test_report.log
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: flutter_test
      dirExists: test

  report:test:dart:
    run: dart test --file-reporter="json:test_report.log"
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: test
      dirExists: test

  # @deprecated `melos format` で代用可能
  # ローカルでフォーマットとdart fix --applyを実行する
  format_and_fix:
    exec: bash "$MELOS_ROOT_PATH/scripts/format.sh"

  ci:report:custom_lint:
    exec: bash "$MELOS_ROOT_PATH/scripts/report-custom-lint-ci.sh"
    packageFilters:
      dependsOn: custom_lint

  gen: melos run gen:l10n && melos run gen:build

  gen:build:
    run: dart run build_runner build -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  gen:l10n:
    run: flutter gen-l10n
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: flutter_localizations

  update:yumemi_lints:
    exec: dart run yumemi_lints update
    packageFilters:
      dependsOn: yumemi_lints

  # `.github/labeler.yml` のパッケージ部分を生成する
  gen:labeler: dart run ./tools/gen_labeler.dart

  # `.github/labels.yml` のパッケージ部分を生成する
  gen:labels: dart run ./tools/gen_labels.dart

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
