name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.2.3
      flutter: ^3.16.4
    dev_dependencies:
      yumemi_lints: ^1.3.0

scripts:
  report_test:
    exec: flutter test --no-pub --machine > test_report.log
    packageFilters:
      flutter: true
      
  format:
    exec: bash "$MELOS_ROOT_PATH/scripts/auto-format.sh"
    # It's permissible for the CI to run even if not branched off directly from the main branch.
    packageFilters: 
      diff: origin/main...HEAD

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
