name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*
  - packages/samples/*
  - packages/utils/*
  - samples/*

command:
  bootstrap:
    environment:
      sdk: ^3.5.4
      flutter: ^3.24.5
    dependencies:
      flutter_hooks: ^0.20.5
      flutter_riverpod: ^2.6.1
      freezed_annotation: ^2.4.4
      hooks_riverpod: ^2.5.1
      intl: ^0.19.0
      json_annotation: ^4.9.0
      riverpod_annotation: ^2.6.1
      go_router: ^14.6.2
    dev_dependencies:
      build_runner: ^2.4.11
      custom_lint: ^0.7.0
      freezed: ^2.5.2
      json_serializable: ^6.8.0
      riverpod_generator: ^2.4.0
      riverpod_lint: ^2.3.10
      yumemi_lints: ^2.2.0
      test: ^1.25.2
      flutter_gen_runner: ^5.8.0
    hooks:
      post: melos run bootstrap:post

scripts:
  # bootstrap 後に実行する script 群
  bootstrap:post:
    description: bootstrap post hooks
    steps:
      # TODO(tatsutakein): yumemi_lints が最新バージョンに対応した際に再度有効化する
      # - yumemi_lints_update
      - gen:labeler
      - gen:labels

  # dependsOn で or 条件で指定することができないため
  # スクリプトを Flutter と Dart に分けている
  test:
    steps:
      - test_flutter
      - test_dart

  test_flutter:
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: flutter_test
      dirExists: test

  test_dart:
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: test
      dirExists: test

  # dependsOn で or 条件で指定することができないため
  # スクリプトを Flutter と Dart に分けている
  report_test:
    steps:
      - report_test_flutter
      - report_test_dart

  report_test_flutter:
    run: flutter test --no-pub --machine > test_report.log
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: flutter_test
      dirExists: test

  report_test_dart:
    run: dart test --file-reporter="json:test_report.log"
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: test
      dirExists: test

  # ローカルでフォーマットとdart fix --applyを実行する
  format_and_fix:
    exec: bash "$MELOS_ROOT_PATH/scripts/format.sh"

  report_custom_lint:ci:
    exec: bash "$MELOS_ROOT_PATH/scripts/report-custom-lint-ci.sh"
    packageFilters:
      dependsOn: custom_lint

  regenerate_code: melos run regenerate_by_using_gen_l10n && melos run regenerate_by_using_build_runner

  regenerate_by_using_build_runner:
    run: dart run build_runner build -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  regenerate_by_using_gen_l10n:
    run: flutter gen-l10n
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: flutter_localizations

  yumemi_lints_update:
    exec: dart run yumemi_lints update
    packageFilters:
      dependsOn: yumemi_lints

  # `.github/labeler.yml` のパッケージ部分を生成する
  gen:labeler: dart run ./tools/gen_labeler.dart

  # `.github/labels.yml` のパッケージ部分を生成する
  gen:labels: dart run ./tools/gen_labels.dart

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
