name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.2.3
      flutter: ^3.16.4
    dependencies:
      flutter:
        sdk: flutter
      flutter_localizations:
        sdk: flutter
      intl: ^0.18.1
    dev_dependencies:
      yumemi_lints: ^1.3.0

scripts:
  report_test:
    exec: flutter test --no-pub --machine > test_report.log
    packageFilters:
      flutter: true

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
