name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.2.3
      flutter: ^3.16.4
    dev_dependencies:
      yumemi_lints: ^1.3.0

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
