name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.2.3
      flutter: ^3.16.4
    dev_dependencies:
      yumemi_lints: ^1.3.0

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
      
scripts:
  format:
    run: |
      files=$(find . -name "*.dart" -not \( -name "*.freezed.dart" -o -name "*.g.dart" -o -name "*.gen.dart" \))
      for file in $files; do
        # limit jobs to 5
        if [ "$(jobs -r | wc -l)" -ge 5 ]; then
          wait "$(jobs -r -p | head -1)"
        fi
        dart fix --apply "$file" &
      done
      wait

      dart format $files
    packageFilters:
      flutter: true
