name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.3.1
      flutter: ^3.19.3
    dependencies:
      hooks_riverpod: ^2.5.1
      flutter_hooks: ^0.20.5
      flutter_riverpod: ^2.5.1
      freezed_annotation: ^2.4.1
      json_annotation: ^4.8.1
      riverpod_annotation: ^2.3.5
    dev_dependencies:
      build_runner: ^2.4.7
      custom_lint: ^0.6.4
      freezed: ^2.4.7
      json_serializable: ^6.7.1
      riverpod_generator: ^2.4.0
      riverpod_lint: ^2.3.10
      yumemi_lints: ^1.3.0

scripts:
  report_test:
    exec: flutter test --no-pub --machine > test_report.log
    packageFilters:
      flutter: true

  format:
    exec: bash "$MELOS_ROOT_PATH/scripts/format.sh"

  check_format:ci:
    exec: bash "$MELOS_ROOT_PATH/scripts/check-format-ci.sh"

  report_custom_lint:ci:
    exec: bash "$MELOS_ROOT_PATH/scripts/report-custom-lint-ci.sh"
    packageFilters:
      dependsOn: custom_lint

  regenerate_code: melos run regenerate_by_using_gen_l10n && melos run regenerate_by_using_build_runner

  regenerate_by_using_build_runner:
    run: dart run build_runner build -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  regenerate_by_using_gen_l10n:
    run: flutter gen-l10n
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: flutter_localizations

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
