name: search
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.2.3
  flutter: ^3.16.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^1.3.0
