name: cores_ui
description: This package provides a UI that depends on the model class and is used by all packages.
version: 0.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  cores_designsystem: 0.0.0
  cores_model: 0.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^2.2.0

flutter:
