name: internal_debug
description: "This package provides features for Debug Mode"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  accessibility_tools: ^2.6.0
  cores_core:
    path: ../cores/core
  dio: ^5.8.0+1
  features_force_update:
    path: ../features/force_update
  features_maintain:
    path: ../features/maintain
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  path: ^1.9.1
  riverpod_annotation: ^2.6.1
  shake_gesture: ^1.2.0
  talker_flutter: ^4.8.2

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
