name: internal_debug
description: "This package provides features for Debug Mode"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  accessibility_tools: ^2.6.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1
  internal_util_ui:
    path: ../util_ui
  path: ^1.9.1
  riverpod_annotation: ^2.6.1
  shake_gesture: ^1.2.0
  talker_flutter: ^5.0.0

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
