name: "Generate issues Matrix at initialization"
description: "Generate matrix data for creating issues based on initialization of Yumemi Inc. flutter mobile project template"

outputs:
  matrix:
    description: "Generated matrix data for creating issues"
    value: ${{ steps.generate.outputs.matrix }}

runs:
  using: "composite"
  steps:
    # https://github.com/jdx/mise-action
    - name: Setup flutter
      uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
      with:
        install_args: "flutter"

    - name: Generate matrix data
      id: generate
      shell: bash
      run: |
        # Dartスクリプトでmatrix JSONを生成
        matrix=$(dart run scripts/generate_issue_matrix.dart)
        echo "matrix=$matrix" >> $GITHUB_OUTPUT
        echo "Generated matrix:"
        echo "$matrix" | jq .
