targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          include:
            - lib/src/{provider,**/provider}/**.dart
      # https://github.com/dart-lang/source_gen#ignore_for_file
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
            - deprecated_member_use
