name: internal_util_ui
description: ユーティリティUIを定義するパッケージです。
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  test: ^1.25.15
