name: internal_util_ui
description: ユーティリティUIを定義するパッケージです。
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
