targets:
  $default:
    builders:
      freezed:
        # https://github.com/dart-lang/build/blob/master/docs/faq.md#how-do-i-avoid-running-builders-on-unnecessary-inputs
        generate_for:
          include:
            - lib/src/{model,**/model}/**.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/{provider,**/provider}/**.dart
      # https://github.com/dart-lang/source_gen#ignore_for_file
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
            - deprecated_member_use
