targets:
  $default:
    builders:
      flutter_gen_runner:
        options:
          output: lib/src/gen/assets/
          assets:
            outputs:
              package_parameter_enabled: true
