import 'constants.dart';
import 'logger.dart';

/// 自動生成の境界となるインデックスを解決する
int resolveAutoGeneratedIndex({
  required List<String> contentLines,
}) {
  // 自動生成の区切り行を探す
  var autoGeneratedIndex = contentLines.indexWhere(
    (line) => line.contains(autoGeneratedLabelComment),
  );

  // 自動生成を表すコメント行が見つからない場合は最終行までを手動生成部分として取り扱う
  if (autoGeneratedIndex == -1) {
    log(
      [
        'Auto-generated label section not found.',
        'Automatically generated from the end of the file.',
      ].join('\n'),
    );
    autoGeneratedIndex = contentLines.length;
  } else {
    log('''Auto-generated label section found on line ${autoGeneratedIndex + 1}.''');
  }

  return autoGeneratedIndex;
}
