arb-dir: lib/src/l10n
output-dir: lib/src/gen/l10n
template-arb-file: features_{{feature_name.snakeCase()}}_ja.arb
output-localization-file: l10n.dart
output-class: L10n
synthetic-package: false
preferred-supported-locales:
  - ja
  - en
nullable-getter: false
format: true
