targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/src/**.dart
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
            - deprecated_member_use 
