name: internal_domain_model
description: エンティティや値オブジェクトなど、ドメインモデルを定義するパッケージです。
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

dev_dependencies:
  test: ^1.25.15
