name: internal_domain_model
description: エンティティや値オブジェクトなど、ドメインモデルを定義するパッケージです。
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  freezed_annotation: ^3.0.0
  pub_semver: ^2.2.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.0.6
  test: ^1.25.15
