name: internal_domain_model
description: エンティティや値オブジェクトなど、ドメインモデルを定義するパッケージです。
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.7
  test: ^1.25.8
