include: package:yumemi_lints/flutter/3.24/recommended.yaml

analyzer:
  plugins:
    # https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint
    - custom_lint
  errors:
    # https://pub.dev/packages/freezed#install
    invalid_annotation_target: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gen.dart'
    - '**/gen/**'
    - '**/.dart_tool/**'
