targets:
  $default:
    builders:
      freezed:
        # https://github.com/dart-lang/build/blob/master/docs/faq.md#how-do-i-avoid-running-builders-on-unnecessary-inputs
        generate_for:
          include:
            - lib/{model,**/model}/**.dart
            - lib/configuration/**.dart
      # https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration
      json_serializable:
        generate_for:
          include:
            - lib/{model,**/model}/**.dart
        options:
          field_rename: snake
          # json のデシリアライズ時に発生する Exception を CheckedFromJsonException にまとめる
          checked: true
      riverpod_generator:
        generate_for:
          include:
            - lib/{providers,**/providers}/**.dart
            - lib/{composition_root,**/composition_root}/**.dart
            - lib/router/router.dart
            # ページファイル内で navigatorProvider を定義できるようにする
            - lib/**/*_page.dart
      # https://github.com/dart-lang/source_gen#ignore_for_file
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
            - deprecated_member_use
      flutter_gen_runner:
        options:
          output: lib/gen/assets/
