name: "Cleanup Copilot Settings"
description: "Cleanup Copilot settings in settings.json file"

inputs:
  settings-json-path:
    description: "Path to the settings.json file"
    default: ".vscode/settings.json"
  temp-json-path:
    description: "Path to the temp.json file"
    default: "temp.json"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      # https://github.com/actions/setup-node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2

    - name: Install jq
      # https://github.com/dcarbone/install-jq-action
      uses: dcarbone/install-jq-action@8867ddb4788346d7c22b72ea2e2ffe4d514c7bcb # v2.1.0

    - name: Install strip-json-comments-cli
      # https://www.npmjs.com/package/strip-json-comments-cli
      run: npm install -g strip-json-comments-cli
      shell: sh

    - name: Strip comments from settings.json
      run: strip-json-comments ${{ inputs.settings-json-path }} > ${{ inputs.temp-json-path }}
      shell: sh

    - name: Edit Json
      # https://github.com/jqlang/jq
      run: >
        jq -n -f ${{ inputs.temp-json-path }} |
        jq '
        ."github.copilot.enable" |= {"*": false} |
        ."github.copilot.editor.enableCodeActions" |= false |
        ."github.copilot.editor.enableAutoCompletions" |= false
        '
        > ${{ inputs.settings-json-path }}
      shell: sh

    - name: Remove temp
      run: rm ${{ inputs.temp-json-path }}
      shell: sh

    - name: Show settings.json
      run: cat ${{ inputs.settings-json-path }}
      shell: sh
