name: "Setup Application Runtime"
description: "Setup application runtime for Flutter"

runs:
  using: "composite"
  steps:

    # https://github.com/jdx/mise-action
    - name: Setup flutter
      uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
      with:
        install_args: "flutter"
        cache: true

    - name: Resolve dependencies
      run: dart pub get
      shell: bash

    - name: Setup melos
      run: |
        MELOS_VERSION=$(cat pubspec.lock | yq ".packages.melos.version" -r)
        dart pub global activate melos $MELOS_VERSION
        dart pub global run melos bootstrap --sdk-path $(mise where flutter)
      shell: bash
